# Hyperledger Fabric Crypto Configuration
# This file defines the network topology for cryptogen
# 3 RAFT Orderers + 3 Peers in 1 Organization

# Orderer Organization Configuration
OrdererOrgs:
  - Name: OrdererOrg
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
        SANS:
          - localhost
      - Hostname: orderer1  
        SANS:
          - localhost
      - Hostname: orderer2
        SANS:
          - localhost

# Peer Organizations Configuration  
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      Count: 3
      SANS:
        - localhost
    Users:
      Count: 1